### ISSUE TITLE
Consider adding PS4 media player to Home Assistant core?

### ISSUE THREAD

**Issue by thibmaek** [hmn/home-assistant-config#10]
This component is super cool! Truly way beter than not having it or just having the switch.

Any reason why you don't PR this to the main repo? Think a lot of people would be thankful for adding this to hass core :)

**Comment by hmn** [comment]
it requires nodejs because ps4-waker is written in node, and the default installations do not have node, so it's not really possible to commit to the main repos.

https://community.home-assistant.io/t/repository-few-addons/20659/7 this guy did some addon stuff for hass.io where ps4-waker is running seperately, so this could maybe be a solution, but if so there needs to be a more generic way of running it so no matter if you run hass.io, docker og locally you can use the component.

the alternative would be to have a python version of ps4-waker, but thats not really a small task either.

unfortunately I have not had time to look further into this

**Comment by psinide** [comment]
Do you know how this can be added to HASS.io as an add-on?

**Comment by hmn** [comment]
I have not looked into it but take a look at what vkorn did on https://community.home-assistant.io/t/repository-few-addons/20659/6

**Comment by thibmaek** [comment]
@hmn @psinide I saw this but just installing the Hass.io addon didn't really do anything. I can't seem to get the component by just installing the add-on

**Comment by hthiery** [comment]
Hi all, anybody still interested in getting this component upstream?

I'm working on pure python implementation of the ps4-wake(r). I think this should be the first step to have a chance for the successfull pull-request.

@hmn: are you willing in porting your custom component to the python implemenation of ps4-waker?

**Comment by hmn** [comment]
@hthiery sure if you manage to create a python lib i'll look into porting it

and if you create a more generic lib instead of a command you need to run, I guess we can make the registration process inside home assistant using the discovery and setup functionality

**Comment by hthiery** [comment]
That sounds good. I will prepare an early version and inform you when it is available. I think the following should be implemented for the homeassistant component.

- discovery of playstations
- get info (e.g. current running app)
- powerup (maybe with automtic login like ps4-waker)
- poweroff

something I miss?

**Comment by hmn** [comment]
I think "start application" is missing as it is needed using the select source functionality

**Comment by hthiery** [comment]
please take a look on: https://github.com/hthiery/python-ps4 and if possible give feedback

**Comment by hmn** [comment]
I am not an expert in modules in pypi but it seems the structure is a bit off for me to include it in a standardiced way in home assistant

it looks like the init described here http://python-packaging.readthedocs.io/en/latest/minimal.html is missing so the naming seems to be off when importing inside home assistant

**Comment by hthiery** [comment]
As i said this is a really early version. Nethertheless finally you only should use the Ps4 class to initialize a new instance and make all stuff with this object.

I added the cli.py as a good starting point for example.

Maybe you can also take a look on one of my other modules that already is included in home-assistant.

https://github.com/hthiery/python-lacrosse

But also for me, I'm not an python expert ;-)

**Comment by hmn** [comment]
do you know what the search data looks like if there are multiple ps4's on the network? I only have one so I can't test if it works with multiple

**Comment by simonk83** [comment]
Super interested in getting this installed in hass.io as well, either officially or otherwise.  Does anyone have it working?

**Comment by hmn** [comment]
@hthiery I added the initial module to a ps4 branch here https://github.com/hmn/home-assistant-dev/tree/ps4 so the basic function to setup a ps4 and get the status works

launch/wakeup is not working for me

shutdown and start app is implemented as missing in the module, so they should be ready to implement when you get them working

**Comment by hthiery** [comment]
Nice to hear. I'm still working on the pyps4 module but struggling with the tcp connection and the encryption used for that.

**Comment by hthiery** [comment]
I think I took a step forward ... now I can login/start app and shutdown. The code is still ugly but first manual tests work.

**Comment by hmn** [comment]
something in docker makes the udp socket fail so in hass.io all of the udp stuff on port 987 does not seem to work

I think it's something with the network components of docker, I tried doing packet traces and manual crafting the packets inside the docker host, but can't seem to figure out why it is failing

any ideas @hthiery ?

**Comment by hthiery** [comment]
@hmn: could you please try to do your tests without that line: https://github.com/hthiery/python-ps4/blob/972cf6349ca36c9c7aebd9388e524dc27727149c/pyps4/ddp.py#L70

I think it is not needed to bind to the address.

How did you try the code? Can you check with the cli tool `ps4-ctrl`?

**Comment by hthiery** [comment]
> something in docker makes the udp socket fail so in hass.io all of the udp stuff on port 987 does not seem to work

do you have a line number where it fails?

**Comment by hmn** [comment]
the ps4 is just not booting, so it's not that it fails

i think it's related to the udp client/server stuff, so whatever the ps4 expects it just does not get it correctly when it's through the docker network

could be because the docker hosts have multiple interfaces or something else, I have not found anything that makes sense, so I think the only way you can test it would be to try to run the pyps4 module inside docker to test it out

I have not tested it in something else than hass.io but I would expect it to fail in all docker environments

**Comment by hmn** [comment]
I have added a docker test/dev setup to https://github.com/hmn/python-ps4 so you can try playing around with that

it requires you test it on a dockers env that is on the same network (docker on mac does not seem to work)

**Comment by hthiery** [comment]
that is good. I see you added it to the other pullrequest.

could you please add it to another pull-request with only these changed files.
