### ISSUE TITLE
Local file for PS4 imagemap

### ISSUE THREAD

**Issue by bieniu** [hmn/home-assistant-config#12]
The component returns an error when the ps4-image map.json file is stored locally. Can you add the ability to store this file in a local directory, eg in the HomeAssistant configuration directory.

**Comment by hmn** [comment]
it is not supported, either you use online resources or you can store images locally by using local_store

read the documentation https://github.com/hmn/home-assistant-config/wiki/media_player_ps4 there are config examples for it

**Comment by bieniu** [comment]
I read the Wiki but I don't understand everything. If you use local_store, the imagemap file isn't needed? If so, what should have the names of image files stored in local_store?

**Comment by hmn** [comment]
the titleid is used, so it would be something like CUSA00127.jpg

**Comment by bieniu** [comment]
OK, thanks for help. I think you could add this information to the Wiki.
