### ISSUE TITLE
Smappee Comfortplugs

### ISSUE THREAD

**Issue by elRadix** [hmn/home-assistant-config#13]
Can you please explain how to use the plugs.
What should be adjusted in order to control these plugs?

Thank you?

ps. https://home-assistant.io/components/switch.smappee/ does not work anymore

**Comment by hmn** [comment]
I don't know where you got the link from, as far as I know it has never been a supported component

usage is documented here https://github.com/hmn/home-assistant-config/wiki/smappee

**Comment by elRadix** [comment]
so controlling the plugs is not supported with this component?

**Comment by hmn** [comment]
yes it is supported, and you need to configure the component.

you need to contact smappee about getting access

it's all described in the documentation

**Comment by elRadix** [comment]
Sorry for not being clear.

Component is already setup and working. I get the sensor data shown in home assistant perfectly.
https://imgur.com/a/72zuC

I'd like to know the command in home assistant to control the plugs, that is not documented only sensor data is documented.

**Comment by hmn** [comment]
they are auto configured so if you have switches they just show up if you configured everything correctly

the switches are controlled via the local smappee api, so it's likely that your hass can't communicate with your smappee box or your login is wrong, I would expect any errors to be logged

**Comment by elRadix** [comment]
strange I do see the sensor data showing up but no switches and no error in the logs
I have copied the sensor and switch folder in the 'custom_components' directory as per documentation.

Entity ID | state
-- | --
sensor.smappee_dageraad_always_on | 33.0
sensor.smappee_dageraad_current | 2288.64
sensor.smappee_dageraad_current_today | 1.78
sensor.smappee_dageraad_solar | 0.0
sensor.smappee_dageraad_solar_today | 0.0

**Comment by elRadix** [comment]
Solved, in fact I was expecting the same naming convention to be switch.smappee.xxxx but instead it was switch.xxxx only, I have a long list of switches hence I overlooked it.

Thank you anyhow for your attention and quick response!!!
