### ISSUE TITLE
Remote key press

### ISSUE THREAD

**Issue by HansWurst90** [hmn/home-assistant-config#16]
Hi,
Thanks for the great component. I love it.
While checking out the code a little bit I found this in the ps4.py:
```
def remote(self, key):
    """Send remote key press."""
    return self.__call('key', key)
```
How can I send a keypress from Home Assistant?

**Comment by hmn** [comment]
it's only used internally, and I don't think the media player component exposes a feature where it would be possible

**Comment by HansWurst90** [comment]
Would it be possible to expose it to be used via a script component?

**Comment by hmn** [comment]
I can't find any examples on any of the other modules exposing extra functionality so I don't think so
