### ISSUE TITLE
Platform not found: media_player.ps4

### ISSUE THREAD

**Issue by aardjoun** [hmn/home-assistant-config#28]
i've got the following issue when setting up ps4 on raspberry pi 3 docker.

`home-assistant   | 2019-01-04 11:36:06 INFO (MainThread) [homeassistant.components.http.view] Serving /api/config/core/check_config to 192.168.1.40 (auth: True)`
`home-assistant   | 2019-01-04 11:36:06 ERROR (SyncWorker_13) [homeassistant.loader] Unable to find component media_player.ps4`

i've attached the volume and change perms to match.
Anyone had the same issue and find a solution ?

**Comment by jlvandusen** [comment]
Yes you need to install the wrapper ps4-waker from vkorn… I added his repository etc... I myself am stuck as I cannot get the tool ps4-waker to run to get the security key... :(
the url for what I did is here:  https://community.home-assistant.io/t/playstation-4-ps4-custom-component/16974/73?u=jlvandusen
