### ISSUE TITLE
Image not updating when not in database

### ISSUE THREAD

**Issue by Mister-Espria** [hmn/home-assistant-config#4]
When starting an game which is in the database an image loads as intended.
When you switch from that game to another game which is not in the database the image will still show the previous game image, but is showing the right game name.
 
When adding this beneath line 112:
`            self._media_image_url = MEDIA_IMAGE_DEFAULT`
It kind of solves it. But it seems quite a long time between updating the image to no-image (not the same time with changing the name). Sometimes it folds the media player to the smaller format with the old image in it and then it disappears.

So this is a solution, but maybe you can come up with a better one 😃

**Comment by hmn** [comment]
year I noticed, I will try to move the image handler or updater around so it is more instant

**Comment by Mister-Espria** [comment]
Ok nice, thanks. i did indeed experience some slowness with the new code compared to my messy code. But less calls to the site was a great improvement.

**Comment by hmn** [comment]
the image handling should now work more responsive

**Comment by Mister-Espria** [comment]
It's way more responsive indeed. But i still managed to get a game image displayed from the previous game. This is the [PR](https://github.com/hmn/home-assistant-config/pull/5) which seems to fix it.
