### ISSUE TITLE
Command Failed

### ISSUE THREAD

**Issue by psinide** [hmn/home-assistant-config#8]
Hi,
I followed your instructions and added PS4 as a media player on HAS. When I try to switch on the PS4 via HAS, it gives me the following error:
```
Jul 15 11:43:54 osmc sudo[3054]: pam_unix(sudo:auth): auth could not identify password for [homeassistant]
Jul 15 11:43:54 osmc sudo[3054]: homeassistant : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ps4-waker -c /home/homeassistant/.homeassistant/ps4-wake.credentials.json -d 192.168.11.100 -t 5000 search
Jul 15 11:43:54 osmc hass[2739]: 2017-07-15 11:43:54 ERROR (Thread-1) [custom_components.media_player.ps4] Command failed: sudo ps4-waker -c /home/homeassistant/.homeassistant/ps4-wake.credentials.json -d 192.168.11.100 -t 5000 search
```
but when I run the above command from CLI, I am getting results and all the details of the PS4. a sudo ps4-wake from the CLI wakes up the PS4 as well.

Will I need to add the homeassistant user to sudoers?

**Comment by hmn** [comment]
it's a local problem with sudo not configured, and has noting to do with the plugin

so you need to make the command work in command line as the homeassistant user before you start using the plugin

**Comment by psinide** [comment]
Thanks for the quick response. I'm fairly new to this, could help me with how to do that? Do I have to add homeassistant to sudoers? If so, I'm not exactlysure how to do that either :(
