### ISSUE TITLE
Use Playstation Store API to fetch images. 

### ISSUE THREAD

**Issue by Zn4rK** [hmn/home-assistant-config#9]
The Playstation Store exposes a API that could be used to fetch images. 
It took me a while to find it, but I wanted to share it so maybe someone could get started on building support for it - I don't have the time right now. 

It's pretty easy really. The media_id that ps4-waker returns is actually a titleId that the Playstation Store uses for "short" links. 
https://store.playstation.com/#!/en-us/tid=CUSA01163_00

When the store has resolved, the web client makes a request to their internal API that looks like this:
https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/US/en/999/CUSA01163_00

The JSON result contains loads of interesting stuff, but the one we are after is most likely the property "images", directly on the root. 

It contains an array with type and url:
```
"images": [{
		"type": 1,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/54f7iSCcukSulKPOT4nVY7Eb6O3eLWhT.png"
	}, {
		"type": 2,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/b0ecnXCagHJTo25UtPhMtfqNDpdrggNE.png"
	}, {
		"type": 9,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/E6R9ilvfgumGikvkkR65VX3ebeqUuBzY.png"
	}, {
		"type": 10,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/1BsGxtWsm6CUhR4eIyuk0GhLmaDAzEvJ.png"
	}, {
		"type": 12,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/L9VwuuaVPBdiwPJOHICsttncxBesDsAr.jpg"
	}, {
		"type": 13,
		"url": "https://apollo2.dl.playstation.net/cdn/UP2002/CUSA01163_00/zYeuydPGpFwFoVaLu62ixDRajMF7yMjQ.png"
	}],
```

I haven't figured out what the different types are for, but I imagine this could be really useful.
The only thing that needs to be done to use this API, is to pad the media_id with "_00".

**Comment by Zn4rK** [comment]
It also seems that theres another part of their API that could be used. And that's their image generator. 

https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/SE/en/999/CUSA01163_00/image?w=800&h=800

By appending "/image" to the above endpoint, we can get the game icon the PS store has selected. It's also possible to pass in querystrings to specify some details (like width and height) for the returned image.

**Comment by thibmaek** [comment]
This would be awesome, I'd try and PR this in myself but have no clue how to follow a redirect with `requests` lib for the first url :/

**Comment by thibmaek** [comment]
Seems like the url path should work if you just correctly interpolate the region and game id into the string.

For example: `https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/BE/nl/999/CUSA01433_00` could be interpolated with `https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/(%country)/(%lang)/999/(%gameid)_00`. Not sure if ps4-waker/home assistant exposes the region though.

**Comment by Zn4rK** [comment]
Ah, you don't have to follow the redirect with the first URL. Just use the second one:
https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/US/en/999/CUSA01163_00

That would give you the JSON response without the redirect...

**Comment by thibmaek** [comment]
Yeah I was checking out if the url was universal since there was also a url which provided the same json response but had another path /api-chihiro/ instead of api/chihuro.

But yeah seems like my last comment could potentially work. I have very little Python knowledge right now but might try it next week perhaps.

**Comment by Zn4rK** [comment]
Sorry, I removed my comment. I noticed that you figured it out. 

We could do a bit of investigation and just have a few countries/locales and do a fallback to another if it doesn't return an image...

**Comment by Zn4rK** [comment]
If we go down the country/lang route, this might be of interest as well;
GET `https://store.playstation.com/kamaji/api/chihiro/00_09_000/geo`

POST `https://store.playstation.com/kamaji/api/chihiro/00_09_000/user/session`

Edit: The above post request doesn't set the session if you don't load another resource it seems. I can't find it right now...

**Comment by thibmaek** [comment]
Actually I don't think it is needed to do GET requests with geo since the US id seems to work regardless of the region. Makes it a lot easier since it doesn't check the id matches the region; thus can default to US/en/<game_id>

I'll see if I can cook this up later next week :)

US ID: `https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/BE/nl/999/CUSA01163_00`
EU ID: `https://store.playstation.com/store/api/chihiro/00_09_000/titlecontainer/BE/nl/999/CUSA01433_00`

**Comment by hmn** [comment]
nice find

it looks like it would be pretty easy to implement

unfortunately I don't have a lot of time for it right now, but if any of you have time to implement it into the component you are more than welcome :)
